# Generated by Django 5.0.1 on 2024-01-14 06:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('acnt', '0002_alter_user_is_freelancer'),
    ]

    operations = [
        migrations.CreateModel(
            name='Location',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('locNames', models.CharField(default='', max_length=50)),
            ],
        ),
        migrations.AddField(
            model_name='client',
            name='loc',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='acnt.location'),
        ),
        migrations.AddField(
            model_name='freelancer',
            name='location',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='acnt.location'),
        ),
    ]
